export const siteConfig = {
  name: "HAUTLAB + Dr. Salvador Cordero",
  doctorName: "Dr. Salvador Cordero",
  legalDoctorName: "Dr. Salvador Cordero Romero",
  professionalTitle: "Médico Cirujano",
  practiceArea: "Dermatología Clínica y Estética",
  professionalLicense: "Cédula Profesional 11804418",
  platformName: "HAUTLAB",
  title: "Dermatología clínica y estética en Mérida | HAUTLAB",
  description:
    "Valoración de piel, cabello y uñas, diseño facial y medicina estética en Mérida con el Dr. Salvador Cordero. Diagnóstico primero y seguimiento clínico.",
  url: "https://www.hautlabmx.com",
  doctorProfilePath: "/dr-salvador-cordero",
  doctorProfileUrl: "https://www.hautlabmx.com/dr-salvador-cordero",
  whatsappNumber: "529992809758",
  whatsappDisplay: "+52 999 280 9758",
  instagram: "https://www.instagram.com/dr.salvadorcordero",
  instagramHandle: "@dr.salvadorcordero",
  googleMaps: "https://maps.app.goo.gl/8CoPkGjpuYDi8QqE6?g_st=ic",
  doctoralia: "https://www.doctoralia.com.mx/perfil/salvador-cordero-romero-2",
  linkedin: "https://mx.linkedin.com/in/salvador-cordero-787337a3",
  pubmedArticles: [
    "https://pubmed.ncbi.nlm.nih.gov/28777905/",
    "https://pubmed.ncbi.nlm.nih.gov/28779584/"
  ],
  privacyEmail: "dr.salvadorcordero@gmail.com",
  privacyUpdated: "11 de julio de 2026",
  address: "Calle 43 número 299A x 32A, San Ramón Norte, C.P. 97117, Mérida, Yucatán",
  mapQuery: "Dr. Salvador Cordero, Dermatología Clínica y Estética, Calle 43 299A, San Ramón Norte, 97117 Mérida, Yucatán",
  location: "Mérida, Yucatán",
  tagline: "Precisión médica. Estética contenida.",
  triad: "Diagnóstico primero. Procedimientos por indicación. Resultados sobrios.",
  philosophy: "No hago procedimientos. Rediseño rostros.",
  consultationPrice: "$1,300 MXN",
  hours: "Lunes a sábado · atención con cita previa"
};
