export const siteConfig = {
  name: "HAUTLAB + Dr. Salvador Cordero",
  doctorName: "Dr. Salvador Cordero",
  legalDoctorName: "Dr. Salvador Cordero Romero",
  professionalTitle: "Médico Cirujano",
  practiceArea: "Dermatología Clínica y Estética",
  professionalLicense: "Cédula Profesional 11804418",
  platformName: "HAUTLAB",
  title: "HAUTLAB + Dr. Salvador Cordero | Piel y diseño facial en Mérida",
  description:
    "Precisión médica. Estética contenida. Valoración de piel, diseño facial y procedimientos por indicación en Mérida, con resultados sobrios.",
  url: "https://www.hautlabmx.com",
  whatsappNumber: "529992809758",
  whatsappDisplay: "+52 999 280 9758",
  instagram: "https://www.instagram.com/dr.salvadorcordero",
  instagramHandle: "@dr.salvadorcordero",
  privacyEmail: "dr.salvadorcordero@gmail.com",
  privacyUpdated: "11 de julio de 2026",
  address: "Calle 43 número 299A x 32A, San Ramón Norte, C.P. 97117, Mérida, Yucatán",
  mapQuery: "Dr. Salvador Cordero, Dermatología Clínica y Estética, Calle 43 299A, San Ramón Norte, 97117 Mérida, Yucatán",
  location: "Mérida, Yucatán",
  tagline: "Precisión médica. Estética contenida.",
  triad: "Diagnóstico primero. Procedimientos por indicación. Resultados sobrios.",
  philosophy: "No hago procedimientos. Rediseño rostros.",
  consultationPrice: "$1,300 MXN",
  hours: "Lunes a sábado · atención con cita previa"
};
