-- P2 payment reconciliation + structured receipts
-- Mercado Pago remains transaction authority. Receipts are derived, server-only projections.
-- CFDI remains a separate billing concern.

create table if not exists public.payment_receipts (
  id uuid primary key default gen_random_uuid(),
  receipt_number bigint generated by default as identity unique,
  source_provider text not null check (
    source_provider in ('mercado_pago', 'mercado_pago_point')
  ),
  source_reference text not null,
  source_payment_id text,
  source_order_id text,
  payment_status text not null,
  receipt_status text not null check (
    receipt_status in ('issued', 'refunded', 'charged_back')
  ),
  amount numeric(12,2) not null check (amount > 0),
  currency text not null default 'MXN' check (currency = 'MXN'),
  paid_at timestamptz not null,
  payment_method_id text,
  payment_type_id text,
  installments integer check (installments is null or installments > 0),
  live_mode boolean,
  test_mode boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_provider, source_reference)
);

create index if not exists payment_receipts_paid_at_idx
  on public.payment_receipts (paid_at desc);
create index if not exists payment_receipts_status_paid_at_idx
  on public.payment_receipts (receipt_status, paid_at desc);
create index if not exists payment_receipts_source_payment_idx
  on public.payment_receipts (source_provider, source_payment_id)
  where source_payment_id is not null;

create table if not exists public.payment_receipt_items (
  receipt_id uuid not null references public.payment_receipts(id) on delete cascade,
  line_no smallint not null check (line_no > 0),
  item_code text,
  label text not null check (char_length(label) between 1 and 180),
  quantity numeric(12,3) not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null check (unit_price >= 0),
  discount_amount numeric(12,2) not null default 0 check (discount_amount >= 0),
  line_total numeric(12,2) not null check (line_total >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (receipt_id, line_no)
);

alter table public.payment_receipts enable row level security;
alter table public.payment_receipt_items enable row level security;

revoke all on table public.payment_receipts from anon, authenticated;
revoke all on table public.payment_receipt_items from anon, authenticated;
grant select, insert, update on table public.payment_receipts to service_role;
grant select, insert, update on table public.payment_receipt_items to service_role;
grant usage, select on sequence public.payment_receipts_receipt_number_seq to service_role;

drop trigger if exists payment_receipts_set_updated_at on public.payment_receipts;
create trigger payment_receipts_set_updated_at
before update on public.payment_receipts
for each row execute function private.hautlab_set_updated_at();

drop trigger if exists payment_receipt_items_set_updated_at on public.payment_receipt_items;
create trigger payment_receipt_items_set_updated_at
before update on public.payment_receipt_items
for each row execute function private.hautlab_set_updated_at();

-- Preserve the provider's date_approved even when the first observed state is
-- refunded/charged_back after a missed webhook.
create or replace function public.hautlab_payment_apply_status(
  p_order_id uuid,
  p_mp_payment_id text,
  p_status text,
  p_status_detail text,
  p_live_mode boolean,
  p_payment_method_id text,
  p_payment_type_id text,
  p_issuer_id text,
  p_paid_at timestamptz,
  p_webhook_event_id text
)
returns setof public.payment_orders
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_status not in (
    'pending',
    'approved',
    'authorized',
    'in_process',
    'in_mediation',
    'rejected',
    'cancelled',
    'refunded',
    'charged_back'
  ) then
    raise exception 'payment_status_not_allowed' using errcode = 'P0001';
  end if;

  return query
  update public.payment_orders
     set mp_payment_id = p_mp_payment_id,
         status = case
           when payment_orders.status in ('refunded', 'charged_back')
             and p_status not in ('refunded', 'charged_back')
             then payment_orders.status
           when payment_orders.status = 'approved'
             and p_status in ('pending', 'authorized', 'in_process', 'in_mediation', 'rejected')
             then payment_orders.status
           else p_status
         end,
         status_detail = p_status_detail,
         live_mode = p_live_mode,
         payment_method_id = p_payment_method_id,
         payment_type_id = p_payment_type_id,
         issuer_id = p_issuer_id,
         last_webhook_event_id = coalesce(p_webhook_event_id, payment_orders.last_webhook_event_id),
         last_webhook_at = case
           when p_webhook_event_id is not null then now()
           else payment_orders.last_webhook_at
         end,
         paid_at = coalesce(
           payment_orders.paid_at,
           p_paid_at,
           case when p_status = 'approved' then now() else null end
         )
   where id = p_order_id
     and test_mode = not p_live_mode
  returning *;

  if not found then
    raise exception 'payment_order_not_found_or_mode_mismatch' using errcode = 'P0001';
  end if;
end;
$$;

revoke all on function public.hautlab_payment_apply_status(
  uuid, text, text, text, boolean, text, text, text, timestamptz, text
) from public, anon, authenticated;
grant execute on function public.hautlab_payment_apply_status(
  uuid, text, text, text, boolean, text, text, text, timestamptz, text
) to service_role;

create or replace function private.hautlab_sync_checkout_receipt()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_receipt_id uuid;
  v_receipt_status text;
begin
  if new.status not in ('approved', 'refunded', 'charged_back') then
    return new;
  end if;

  v_receipt_status := case
    when new.status = 'refunded' then 'refunded'
    when new.status = 'charged_back' then 'charged_back'
    else 'issued'
  end;

  insert into public.payment_receipts (
    source_provider,
    source_reference,
    source_payment_id,
    source_order_id,
    payment_status,
    receipt_status,
    amount,
    currency,
    paid_at,
    payment_method_id,
    payment_type_id,
    live_mode,
    test_mode
  ) values (
    'mercado_pago',
    new.external_reference,
    new.mp_payment_id,
    new.preference_id,
    new.status,
    v_receipt_status,
    new.amount,
    new.currency,
    coalesce(new.paid_at, new.updated_at, now()),
    new.payment_method_id,
    new.payment_type_id,
    new.live_mode,
    new.test_mode
  )
  on conflict (source_provider, source_reference) do update
    set source_payment_id = coalesce(excluded.source_payment_id, public.payment_receipts.source_payment_id),
        source_order_id = coalesce(excluded.source_order_id, public.payment_receipts.source_order_id),
        payment_status = excluded.payment_status,
        receipt_status = excluded.receipt_status,
        paid_at = least(public.payment_receipts.paid_at, excluded.paid_at),
        payment_method_id = coalesce(excluded.payment_method_id, public.payment_receipts.payment_method_id),
        payment_type_id = coalesce(excluded.payment_type_id, public.payment_receipts.payment_type_id),
        live_mode = coalesce(excluded.live_mode, public.payment_receipts.live_mode),
        updated_at = now()
  returning id into v_receipt_id;

  insert into public.payment_receipt_items (
    receipt_id,
    line_no,
    item_code,
    label,
    quantity,
    unit_price,
    discount_amount,
    line_total
  ) values (
    v_receipt_id,
    1,
    new.product_code,
    new.product_label,
    1,
    new.amount,
    0,
    new.amount
  )
  on conflict (receipt_id, line_no) do update
    set item_code = excluded.item_code,
        label = excluded.label,
        unit_price = excluded.unit_price,
        line_total = excluded.line_total,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists payment_orders_sync_receipt on public.payment_orders;
create trigger payment_orders_sync_receipt
after update on public.payment_orders
for each row execute function private.hautlab_sync_checkout_receipt();

create or replace function private.hautlab_sync_point_receipt()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_receipt_id uuid;
  v_receipt_status text;
begin
  if new.status not in ('processed', 'refunded') then
    return new;
  end if;

  v_receipt_status := case
    when new.status = 'refunded' then 'refunded'
    else 'issued'
  end;

  insert into public.payment_receipts (
    source_provider,
    source_reference,
    source_payment_id,
    source_order_id,
    payment_status,
    receipt_status,
    amount,
    currency,
    paid_at,
    payment_method_id,
    payment_type_id,
    installments,
    live_mode,
    test_mode
  ) values (
    'mercado_pago_point',
    new.external_reference,
    coalesce(new.payment_reference_id, new.transaction_id),
    new.mp_order_id,
    new.status,
    v_receipt_status,
    new.amount,
    new.currency,
    coalesce(new.paid_at, new.provider_updated_at, new.updated_at, now()),
    new.payment_method_id,
    new.payment_method_type,
    new.installments,
    new.live_mode,
    new.test_mode
  )
  on conflict (source_provider, source_reference) do update
    set source_payment_id = coalesce(excluded.source_payment_id, public.payment_receipts.source_payment_id),
        source_order_id = coalesce(excluded.source_order_id, public.payment_receipts.source_order_id),
        payment_status = excluded.payment_status,
        receipt_status = excluded.receipt_status,
        paid_at = least(public.payment_receipts.paid_at, excluded.paid_at),
        payment_method_id = coalesce(excluded.payment_method_id, public.payment_receipts.payment_method_id),
        payment_type_id = coalesce(excluded.payment_type_id, public.payment_receipts.payment_type_id),
        installments = coalesce(excluded.installments, public.payment_receipts.installments),
        live_mode = coalesce(excluded.live_mode, public.payment_receipts.live_mode),
        updated_at = now()
  returning id into v_receipt_id;

  insert into public.payment_receipt_items (
    receipt_id,
    line_no,
    item_code,
    label,
    quantity,
    unit_price,
    discount_amount,
    line_total
  ) values (
    v_receipt_id,
    1,
    null,
    new.description,
    1,
    new.amount,
    0,
    new.amount
  )
  on conflict (receipt_id, line_no) do update
    set label = excluded.label,
        unit_price = excluded.unit_price,
        line_total = excluded.line_total,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists mp_point_orders_sync_receipt on public.mp_point_orders;
create trigger mp_point_orders_sync_receipt
after update on public.mp_point_orders
for each row execute function private.hautlab_sync_point_receipt();

-- Safe backfill for already-verified paid states.
insert into public.payment_receipts (
  source_provider, source_reference, source_payment_id, source_order_id,
  payment_status, receipt_status, amount, currency, paid_at,
  payment_method_id, payment_type_id, live_mode, test_mode
)
select
  'mercado_pago', external_reference, mp_payment_id, preference_id,
  status,
  case when status = 'refunded' then 'refunded'
       when status = 'charged_back' then 'charged_back'
       else 'issued' end,
  amount, currency, coalesce(paid_at, updated_at),
  payment_method_id, payment_type_id, live_mode, test_mode
from public.payment_orders
where status in ('approved', 'refunded', 'charged_back')
on conflict (source_provider, source_reference) do nothing;

insert into public.payment_receipt_items (
  receipt_id, line_no, item_code, label, quantity, unit_price, discount_amount, line_total
)
select r.id, 1, o.product_code, o.product_label, 1, o.amount, 0, o.amount
from public.payment_receipts r
join public.payment_orders o
  on r.source_provider = 'mercado_pago'
 and r.source_reference = o.external_reference
where not exists (
  select 1 from public.payment_receipt_items i
  where i.receipt_id = r.id and i.line_no = 1
)
on conflict (receipt_id, line_no) do nothing;

insert into public.payment_receipts (
  source_provider, source_reference, source_payment_id, source_order_id,
  payment_status, receipt_status, amount, currency, paid_at,
  payment_method_id, payment_type_id, installments, live_mode, test_mode
)
select
  'mercado_pago_point', external_reference,
  coalesce(payment_reference_id, transaction_id), mp_order_id,
  status, case when status = 'refunded' then 'refunded' else 'issued' end,
  amount, currency, coalesce(paid_at, provider_updated_at, updated_at),
  payment_method_id, payment_method_type, installments, live_mode, test_mode
from public.mp_point_orders
where status in ('processed', 'refunded')
on conflict (source_provider, source_reference) do nothing;

insert into public.payment_receipt_items (
  receipt_id, line_no, item_code, label, quantity, unit_price, discount_amount, line_total
)
select r.id, 1, null, o.description, 1, o.amount, 0, o.amount
from public.payment_receipts r
join public.mp_point_orders o
  on r.source_provider = 'mercado_pago_point'
 and r.source_reference = o.external_reference
where not exists (
  select 1 from public.payment_receipt_items i
  where i.receipt_id = r.id and i.line_no = 1
)
on conflict (receipt_id, line_no) do nothing;
