create extension if not exists pgcrypto;

create table if not exists public.hlstaff_sites (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  address text not null,
  latitude double precision,
  longitude double precision,
  radius_m integer not null default 100 check (radius_m between 25 and 1000),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.hlstaff_sites(code,name,address,radius_m)
values ('merida','HAUTLAB Mérida','Calle 43 #299A x 32A, San Ramón Norte, C.P. 97117, Mérida, Yucatán, México',100)
on conflict (code) do update set name=excluded.name,address=excluded.address;

create table if not exists public.hlstaff_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  operator_key text unique references public.wa_operators(operator_key) on update cascade,
  display_name text not null,
  role text not null default 'staff' check (role in ('manager','staff')),
  base_monthly_salary numeric(12,2) not null default 0,
  commission_rate numeric(6,5) not null default 0.02,
  reactivation_rate numeric(6,5) not null default 0.01,
  active boolean not null default true,
  location_tracking_consent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.hlstaff_schedules (
  id bigint generated by default as identity primary key,
  staff_id uuid not null references public.hlstaff_profiles(id) on delete cascade,
  weekday smallint not null check (weekday between 1 and 7),
  scheduled_start time,
  scheduled_end time,
  grace_minutes integer not null default 5 check (grace_minutes between 0 and 120),
  active boolean not null default true,
  unique(staff_id, weekday)
);

create table if not exists public.hlstaff_shifts (
  id uuid primary key default gen_random_uuid(),
  staff_id uuid not null references public.hlstaff_profiles(id) on delete cascade,
  site_id uuid not null references public.hlstaff_sites(id),
  check_in_at timestamptz not null default now(),
  check_out_at timestamptz,
  check_in_lat double precision not null,
  check_in_lng double precision not null,
  check_in_accuracy_m double precision,
  check_out_lat double precision,
  check_out_lng double precision,
  check_out_accuracy_m double precision,
  check_in_distance_m double precision,
  check_out_distance_m double precision,
  check_in_status text not null default 'pending' check (check_in_status in ('inside','outside','pending')),
  check_out_status text check (check_out_status in ('inside','outside','pending')),
  minutes_late integer not null default 0,
  minutes_outside_geofence integer not null default 0,
  device_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists hlstaff_one_open_shift_per_staff on public.hlstaff_shifts(staff_id) where check_out_at is null;

create table if not exists public.hlstaff_location_events (
  id bigint generated by default as identity primary key,
  shift_id uuid not null references public.hlstaff_shifts(id) on delete cascade,
  staff_id uuid not null references public.hlstaff_profiles(id) on delete cascade,
  event_type text not null check (event_type in ('check_in','check_out','enter','exit','heartbeat','permission_denied','location_unavailable')),
  latitude double precision,
  longitude double precision,
  accuracy_m double precision,
  distance_m double precision,
  inside_geofence boolean,
  created_at timestamptz not null default now()
);
create index if not exists hlstaff_location_events_shift_created_idx on public.hlstaff_location_events(shift_id, created_at);

create table if not exists public.hlstaff_cash_payments (
  id uuid primary key default gen_random_uuid(),
  patient_name text not null,
  patient_phone text,
  conversation_id uuid references public.wa_conversations(id) on delete set null,
  amount numeric(12,2) not null check (amount > 0),
  concept text not null,
  revenue_owner text not null check (revenue_owner in ('karen','doctor','organic','referral')),
  commission_type text not null default 'none' check (commission_type in ('none','standard','reactivation')),
  commission_rate numeric(6,5) not null default 0,
  commission_amount numeric(12,2) generated always as (round(amount * commission_rate,2)) stored,
  captured_by uuid references public.hlstaff_profiles(id) on delete set null,
  paid_at timestamptz not null default now(),
  notes text,
  created_at timestamptz not null default now()
);
create index if not exists hlstaff_cash_paid_at_idx on public.hlstaff_cash_payments(paid_at);

create table if not exists public.hlstaff_payment_attribution (
  id uuid primary key default gen_random_uuid(),
  provider text not null check (provider in ('mercado_pago','point','transfer','other')),
  provider_payment_id text not null,
  conversation_id uuid references public.wa_conversations(id) on delete set null,
  patient_name text,
  revenue_owner text not null check (revenue_owner in ('karen','doctor','organic','referral')),
  commission_type text not null default 'none' check (commission_type in ('none','standard','reactivation')),
  commission_rate numeric(6,5) not null default 0,
  attribution_source text not null default 'manual' check (attribution_source in ('automatic','manual','imported')),
  attributed_by uuid references public.hlstaff_profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  unique(provider, provider_payment_id)
);

create table if not exists public.hlstaff_cash_closures (
  id uuid primary key default gen_random_uuid(),
  site_id uuid not null references public.hlstaff_sites(id),
  closure_date date not null,
  expected_cash numeric(12,2) not null default 0,
  counted_cash numeric(12,2) not null default 0,
  difference numeric(12,2) generated always as (counted_cash - expected_cash) stored,
  closed_by uuid references public.hlstaff_profiles(id) on delete set null,
  notes text,
  created_at timestamptz not null default now(),
  unique(site_id, closure_date)
);

create or replace function public.hlstaff_haversine_m(lat1 double precision, lon1 double precision, lat2 double precision, lon2 double precision)
returns double precision
language sql immutable strict as $$
  select 6371000 * 2 * asin(sqrt(
    power(sin(radians(lat2-lat1)/2),2) +
    cos(radians(lat1))*cos(radians(lat2))*power(sin(radians(lon2-lon1)/2),2)
  ));
$$;

create or replace function public.hlstaff_check_in(p_site_id uuid, p_lat double precision, p_lng double precision, p_accuracy_m double precision default null, p_device_id text default null)
returns public.hlstaff_shifts
language plpgsql security definer set search_path=public as $$
declare
  v_staff public.hlstaff_profiles;
  v_site public.hlstaff_sites;
  v_distance double precision;
  v_sched public.hlstaff_schedules;
  v_late integer := 0;
  v_shift public.hlstaff_shifts;
begin
  select * into v_staff from public.hlstaff_profiles where id=auth.uid() and active=true;
  if v_staff.id is null then raise exception 'STAFF_PROFILE_NOT_FOUND'; end if;
  select * into v_site from public.hlstaff_sites where id=p_site_id and active=true;
  if v_site.id is null then raise exception 'SITE_NOT_FOUND'; end if;
  if v_site.latitude is null or v_site.longitude is null then raise exception 'SITE_NOT_CALIBRATED'; end if;
  if exists(select 1 from public.hlstaff_shifts where staff_id=v_staff.id and check_out_at is null) then raise exception 'OPEN_SHIFT_EXISTS'; end if;
  v_distance := public.hlstaff_haversine_m(p_lat,p_lng,v_site.latitude,v_site.longitude);
  select * into v_sched from public.hlstaff_schedules where staff_id=v_staff.id and weekday=extract(isodow from timezone('America/Merida',now()))::int and active=true;
  if v_sched.id is not null and v_sched.scheduled_start is not null then
    v_late := greatest(0, floor(extract(epoch from ((timezone('America/Merida',now())::time) - v_sched.scheduled_start))/60)::int - v_sched.grace_minutes);
  end if;
  insert into public.hlstaff_shifts(staff_id,site_id,check_in_lat,check_in_lng,check_in_accuracy_m,check_in_distance_m,check_in_status,minutes_late,device_id)
  values(v_staff.id,v_site.id,p_lat,p_lng,p_accuracy_m,v_distance,case when v_distance <= v_site.radius_m then 'inside' else 'outside' end,v_late,p_device_id)
  returning * into v_shift;
  insert into public.hlstaff_location_events(shift_id,staff_id,event_type,latitude,longitude,accuracy_m,distance_m,inside_geofence)
  values(v_shift.id,v_staff.id,'check_in',p_lat,p_lng,p_accuracy_m,v_distance,v_distance <= v_site.radius_m);
  if v_distance > v_site.radius_m then raise exception 'OUTSIDE_GEOFENCE'; end if;
  return v_shift;
exception when others then
  if SQLERRM='OUTSIDE_GEOFENCE' then
    delete from public.hlstaff_shifts where id=v_shift.id;
  end if;
  raise;
end;
$$;

create or replace function public.hlstaff_check_out(p_lat double precision, p_lng double precision, p_accuracy_m double precision default null)
returns public.hlstaff_shifts
language plpgsql security definer set search_path=public as $$
declare
  v_staff public.hlstaff_profiles;
  v_shift public.hlstaff_shifts;
  v_site public.hlstaff_sites;
  v_distance double precision;
begin
  select * into v_staff from public.hlstaff_profiles where id=auth.uid() and active=true;
  if v_staff.id is null then raise exception 'STAFF_PROFILE_NOT_FOUND'; end if;
  select * into v_shift from public.hlstaff_shifts where staff_id=v_staff.id and check_out_at is null order by check_in_at desc limit 1 for update;
  if v_shift.id is null then raise exception 'NO_OPEN_SHIFT'; end if;
  select * into v_site from public.hlstaff_sites where id=v_shift.site_id;
  v_distance := public.hlstaff_haversine_m(p_lat,p_lng,v_site.latitude,v_site.longitude);
  update public.hlstaff_shifts set check_out_at=now(),check_out_lat=p_lat,check_out_lng=p_lng,check_out_accuracy_m=p_accuracy_m,check_out_distance_m=v_distance,check_out_status=case when v_distance <= v_site.radius_m then 'inside' else 'outside' end,updated_at=now() where id=v_shift.id returning * into v_shift;
  insert into public.hlstaff_location_events(shift_id,staff_id,event_type,latitude,longitude,accuracy_m,distance_m,inside_geofence)
  values(v_shift.id,v_staff.id,'check_out',p_lat,p_lng,p_accuracy_m,v_distance,v_distance <= v_site.radius_m);
  return v_shift;
end;
$$;

create or replace function public.hlstaff_log_location(p_shift_id uuid, p_event_type text, p_lat double precision, p_lng double precision, p_accuracy_m double precision default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_staff public.hlstaff_profiles; v_shift public.hlstaff_shifts; v_site public.hlstaff_sites; v_distance double precision;
begin
 select * into v_staff from public.hlstaff_profiles where id=auth.uid() and active=true;
 select * into v_shift from public.hlstaff_shifts where id=p_shift_id and staff_id=v_staff.id and check_out_at is null;
 if v_shift.id is null then raise exception 'OPEN_SHIFT_NOT_FOUND'; end if;
 select * into v_site from public.hlstaff_sites where id=v_shift.site_id;
 v_distance := public.hlstaff_haversine_m(p_lat,p_lng,v_site.latitude,v_site.longitude);
 insert into public.hlstaff_location_events(shift_id,staff_id,event_type,latitude,longitude,accuracy_m,distance_m,inside_geofence)
 values(v_shift.id,v_staff.id,p_event_type,p_lat,p_lng,p_accuracy_m,v_distance,v_distance <= v_site.radius_m);
end; $$;

create or replace view public.hlstaff_revenue_summary_monthly as
select date_trunc('month', paid_at at time zone 'America/Merida')::date as month,
       revenue_owner,
       count(*) as payments,
       sum(amount)::numeric(14,2) as gross_revenue,
       sum(commission_amount)::numeric(14,2) as commission
from public.hlstaff_cash_payments
group by 1,2;

alter table public.hlstaff_sites enable row level security;
alter table public.hlstaff_profiles enable row level security;
alter table public.hlstaff_schedules enable row level security;
alter table public.hlstaff_shifts enable row level security;
alter table public.hlstaff_location_events enable row level security;
alter table public.hlstaff_cash_payments enable row level security;
alter table public.hlstaff_payment_attribution enable row level security;
alter table public.hlstaff_cash_closures enable row level security;

create policy hlstaff_sites_read on public.hlstaff_sites for select to authenticated using (active=true);
create policy hlstaff_profiles_self on public.hlstaff_profiles for select to authenticated using (id=auth.uid() or exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));
create policy hlstaff_profiles_self_update on public.hlstaff_profiles for update to authenticated using (id=auth.uid() or exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager')) with check (id=auth.uid() or exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));
create policy hlstaff_schedules_read on public.hlstaff_schedules for select to authenticated using (staff_id=auth.uid() or exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));
create policy hlstaff_shifts_read on public.hlstaff_shifts for select to authenticated using (staff_id=auth.uid() or exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));
create policy hlstaff_location_read on public.hlstaff_location_events for select to authenticated using (staff_id=auth.uid() or exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));
create policy hlstaff_cash_read on public.hlstaff_cash_payments for select to authenticated using (captured_by=auth.uid() or exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));
create policy hlstaff_cash_insert on public.hlstaff_cash_payments for insert to authenticated with check (captured_by=auth.uid());
create policy hlstaff_attribution_manager on public.hlstaff_payment_attribution for all to authenticated using (exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager')) with check (exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));
create policy hlstaff_closures_manager on public.hlstaff_cash_closures for all to authenticated using (exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager')) with check (exists(select 1 from public.hlstaff_profiles m where m.id=auth.uid() and m.role='manager'));

grant execute on function public.hlstaff_check_in(uuid,double precision,double precision,double precision,text) to authenticated;
grant execute on function public.hlstaff_check_out(double precision,double precision,double precision) to authenticated;
grant execute on function public.hlstaff_log_location(uuid,text,double precision,double precision,double precision) to authenticated;
grant select on public.hlstaff_revenue_summary_monthly to authenticated;
