-- HAUTLAB attendance database for Supabase/PostgreSQL.
-- Run once in the Supabase SQL editor. All application access uses the server-only service role.

create extension if not exists pgcrypto;

create table if not exists public.attendance_profiles (
  user_id text primary key,
  email text not null,
  display_name text not null,
  role text not null check (role in ('manager', 'employee')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance_schedules (
  id bigint generated by default as identity primary key,
  user_id text not null references public.attendance_profiles(user_id) on delete restrict,
  weekday smallint not null check (weekday between 0 and 6),
  scheduled_start time,
  scheduled_end time,
  grace_minutes integer not null default 0 check (grace_minutes between 0 and 180),
  active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, weekday),
  check ((active = false) or (scheduled_start is not null and scheduled_end is not null and scheduled_end > scheduled_start))
);

create table if not exists public.attendance_shifts (
  id uuid primary key default gen_random_uuid(),
  user_id text not null references public.attendance_profiles(user_id) on delete restrict,
  check_in_at timestamptz not null default now(),
  check_out_at timestamptz,
  corrected_check_in_at timestamptz,
  corrected_check_out_at timestamptz,
  reversed_at timestamptz,
  reversal_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (check_out_at is null or check_out_at > check_in_at),
  check (corrected_check_out_at is null or corrected_check_out_at > coalesce(corrected_check_in_at, check_in_at)),
  check ((reversed_at is null and reversal_reason is null) or (reversed_at is not null and length(trim(reversal_reason)) >= 5))
);

create unique index if not exists attendance_one_open_shift_per_user
  on public.attendance_shifts (user_id)
  where coalesce(corrected_check_out_at, check_out_at) is null and reversed_at is null;

create index if not exists attendance_shifts_user_check_in_idx
  on public.attendance_shifts (user_id, check_in_at desc);

create table if not exists public.attendance_audit (
  id uuid primary key default gen_random_uuid(),
  shift_id uuid references public.attendance_shifts(id) on delete restrict,
  target_user_id text not null references public.attendance_profiles(user_id) on delete restrict,
  actor_user_id text not null,
  actor_email text not null,
  action text not null check (action in ('check_in', 'check_out', 'correction', 'reversal', 'schedule_change')),
  reason text not null check (length(trim(reason)) >= 5),
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists attendance_audit_target_created_idx
  on public.attendance_audit (target_user_id, created_at desc);

alter table public.attendance_profiles enable row level security;
alter table public.attendance_schedules enable row level security;
alter table public.attendance_shifts enable row level security;
alter table public.attendance_audit enable row level security;

revoke all on public.attendance_profiles from anon, authenticated;
revoke all on public.attendance_schedules from anon, authenticated;
revoke all on public.attendance_shifts from anon, authenticated;
revoke all on public.attendance_audit from anon, authenticated;

grant all on public.attendance_profiles to service_role;
grant all on public.attendance_schedules to service_role;
grant all on public.attendance_shifts to service_role;
grant all on public.attendance_audit to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.attendance_protect_original_marks()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.check_in_at is distinct from old.check_in_at then
    raise exception 'attendance_original_check_in_immutable';
  end if;
  if old.check_out_at is not null and new.check_out_at is distinct from old.check_out_at then
    raise exception 'attendance_original_check_out_immutable';
  end if;
  return new;
end;
$$;

drop trigger if exists attendance_protect_original_marks on public.attendance_shifts;
create trigger attendance_protect_original_marks
before update on public.attendance_shifts
for each row execute function public.attendance_protect_original_marks();

create or replace function public.attendance_register_profile(
  p_user_id text,
  p_email text,
  p_display_name text,
  p_role text
)
returns setof public.attendance_profiles
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_user_id is null or length(trim(p_user_id)) = 0 then raise exception 'attendance_user_id_required'; end if;
  if p_email is null or length(trim(p_email)) = 0 then raise exception 'attendance_email_required'; end if;
  if p_role not in ('manager', 'employee') then raise exception 'attendance_invalid_role'; end if;

  insert into public.attendance_profiles (user_id, email, display_name, role)
  values (trim(p_user_id), lower(trim(p_email)), coalesce(nullif(trim(p_display_name), ''), lower(trim(p_email))), p_role)
  on conflict (user_id) do update
  set email = excluded.email,
      display_name = excluded.display_name,
      role = excluded.role,
      updated_at = now();

  return query select * from public.attendance_profiles where user_id = trim(p_user_id);
end;
$$;

create or replace function public.attendance_punch(
  p_user_id text,
  p_email text,
  p_display_name text,
  p_role text,
  p_action text
)
returns setof public.attendance_shifts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_shift public.attendance_shifts%rowtype;
  v_now timestamptz := now();
begin
  perform pg_advisory_xact_lock(hashtext(p_user_id));
  perform public.attendance_register_profile(p_user_id, p_email, p_display_name, p_role);

  if p_action = 'check_in' then
    if exists (
      select 1 from public.attendance_shifts
      where user_id = p_user_id
        and coalesce(corrected_check_out_at, check_out_at) is null
        and reversed_at is null
    ) then
      raise exception 'attendance_shift_already_open';
    end if;

    insert into public.attendance_shifts (user_id, check_in_at)
    values (p_user_id, v_now)
    returning * into v_shift;

    insert into public.attendance_audit (
      shift_id, target_user_id, actor_user_id, actor_email, action, reason, before_data, after_data
    ) values (
      v_shift.id, p_user_id, p_user_id, lower(trim(p_email)), 'check_in',
      'Marca de entrada del usuario', null, to_jsonb(v_shift)
    );
  elsif p_action = 'check_out' then
    select * into v_shift
    from public.attendance_shifts
    where user_id = p_user_id
      and coalesce(corrected_check_out_at, check_out_at) is null
      and reversed_at is null
    order by check_in_at desc
    limit 1
    for update;

    if not found then raise exception 'attendance_no_open_shift'; end if;

    update public.attendance_shifts
    set check_out_at = v_now, updated_at = v_now
    where id = v_shift.id
    returning * into v_shift;

    insert into public.attendance_audit (
      shift_id, target_user_id, actor_user_id, actor_email, action, reason, before_data, after_data
    ) values (
      v_shift.id, p_user_id, p_user_id, lower(trim(p_email)), 'check_out',
      'Marca de salida del usuario', null, to_jsonb(v_shift)
    );
  else
    raise exception 'attendance_invalid_action';
  end if;

  return next v_shift;
end;
$$;

create or replace function public.attendance_correct_shift(
  p_shift_id uuid,
  p_target_user_id text,
  p_actor_user_id text,
  p_actor_email text,
  p_corrected_check_in_at timestamptz,
  p_corrected_check_out_at timestamptz,
  p_reverse boolean,
  p_reason text
)
returns setof public.attendance_shifts
language plpgsql
security definer
set search_path = public
as $$
declare
  v_before public.attendance_shifts%rowtype;
  v_after public.attendance_shifts%rowtype;
begin
  if p_reason is null or length(trim(p_reason)) < 5 then raise exception 'attendance_correction_reason_required'; end if;
  perform pg_advisory_xact_lock(hashtext(p_target_user_id));

  select * into v_before
  from public.attendance_shifts
  where id = p_shift_id and user_id = p_target_user_id
  for update;

  if not found then raise exception 'attendance_shift_not_found'; end if;

  if p_reverse then
    if v_before.reversed_at is not null then raise exception 'attendance_shift_already_reversed'; end if;
    update public.attendance_shifts
    set reversed_at = now(), reversal_reason = trim(p_reason), updated_at = now()
    where id = p_shift_id
    returning * into v_after;
  else
    if p_corrected_check_in_at is null then raise exception 'attendance_corrected_check_in_required'; end if;
    if p_corrected_check_out_at is not null and p_corrected_check_out_at <= p_corrected_check_in_at then
      raise exception 'attendance_invalid_corrected_range';
    end if;
    update public.attendance_shifts
    set corrected_check_in_at = p_corrected_check_in_at,
        corrected_check_out_at = p_corrected_check_out_at,
        updated_at = now()
    where id = p_shift_id
    returning * into v_after;
  end if;

  insert into public.attendance_audit (
    shift_id, target_user_id, actor_user_id, actor_email, action, reason, before_data, after_data
  ) values (
    p_shift_id, p_target_user_id, p_actor_user_id, lower(trim(p_actor_email)),
    case when p_reverse then 'reversal' else 'correction' end,
    trim(p_reason), to_jsonb(v_before), to_jsonb(v_after)
  );

  return next v_after;
end;
$$;

create or replace function public.attendance_replace_schedule(
  p_target_user_id text,
  p_actor_user_id text,
  p_actor_email text,
  p_reason text,
  p_schedule jsonb
)
returns setof public.attendance_schedules
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item record;
  v_before jsonb;
begin
  if p_reason is null or length(trim(p_reason)) < 5 then raise exception 'attendance_schedule_reason_required'; end if;
  if jsonb_typeof(p_schedule) <> 'array' or jsonb_array_length(p_schedule) <> 7 then raise exception 'attendance_invalid_schedule'; end if;
  if not exists (select 1 from public.attendance_profiles where user_id = p_target_user_id) then raise exception 'attendance_profile_not_found'; end if;

  perform pg_advisory_xact_lock(hashtext(p_target_user_id));
  select coalesce(jsonb_agg(to_jsonb(s) order by s.weekday), '[]'::jsonb)
    into v_before
  from public.attendance_schedules s
  where s.user_id = p_target_user_id;

  for v_item in
    select * from jsonb_to_recordset(p_schedule) as x(
      weekday integer,
      active boolean,
      scheduled_start time,
      scheduled_end time,
      grace_minutes integer
    )
  loop
    if v_item.weekday < 0 or v_item.weekday > 6 then raise exception 'attendance_invalid_weekday'; end if;
    if v_item.grace_minutes < 0 or v_item.grace_minutes > 180 then raise exception 'attendance_invalid_grace'; end if;
    if v_item.active and (
      v_item.scheduled_start is null or v_item.scheduled_end is null or v_item.scheduled_end <= v_item.scheduled_start
    ) then raise exception 'attendance_invalid_schedule_range'; end if;

    insert into public.attendance_schedules (
      user_id, weekday, active, scheduled_start, scheduled_end, grace_minutes
    ) values (
      p_target_user_id, v_item.weekday, v_item.active,
      case when v_item.active then v_item.scheduled_start else null end,
      case when v_item.active then v_item.scheduled_end else null end,
      case when v_item.active then v_item.grace_minutes else 0 end
    )
    on conflict (user_id, weekday) do update
    set active = excluded.active,
        scheduled_start = excluded.scheduled_start,
        scheduled_end = excluded.scheduled_end,
        grace_minutes = excluded.grace_minutes,
        updated_at = now();
  end loop;

  insert into public.attendance_audit (
    shift_id, target_user_id, actor_user_id, actor_email, action, reason, before_data, after_data
  )
  select null, p_target_user_id, p_actor_user_id, lower(trim(p_actor_email)), 'schedule_change',
         trim(p_reason), v_before,
         coalesce(jsonb_agg(to_jsonb(s) order by s.weekday), '[]'::jsonb)
  from public.attendance_schedules s
  where s.user_id = p_target_user_id;

  return query select * from public.attendance_schedules where user_id = p_target_user_id order by weekday;
end;
$$;

revoke all on function public.attendance_register_profile(text, text, text, text) from public, anon, authenticated;
revoke all on function public.attendance_punch(text, text, text, text, text) from public, anon, authenticated;
revoke all on function public.attendance_correct_shift(uuid, text, text, text, timestamptz, timestamptz, boolean, text) from public, anon, authenticated;
revoke all on function public.attendance_replace_schedule(text, text, text, text, jsonb) from public, anon, authenticated;

grant execute on function public.attendance_register_profile(text, text, text, text) to service_role;
grant execute on function public.attendance_punch(text, text, text, text, text) to service_role;
grant execute on function public.attendance_correct_shift(uuid, text, text, text, timestamptz, timestamptz, boolean, text) to service_role;
grant execute on function public.attendance_replace_schedule(text, text, text, text, jsonb) to service_role;
